services:
  - type: web
    name: toon-ai-engine
    env: docker
    plan: free
    region: oregon 
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 5000
      - key: DEBUG
        value: "False"
      - key: APP_NAME
        value: Toonify
      - fromDatabase:
          name: toon-cloud-db-final
          property: connectionString
        key: DATABASE_URL

databases:
  - name: toon-cloud-db-final
    databaseName: toonify_production_v1
    plan: free
    region: oregon
