services:
  - type: web
    name: toonify-ai-saas
    env: docker
    plan: free
    region: oregon 
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 5000
      - key: DEBUG
        value: "False"
      - key: APP_NAME
        value: Toonify
      - fromDatabase:
          name: toonify-db
          property: connectionString
        key: DATABASE_URL

databases:
  - name: toonify-db
    plan: free
    region: oregon
